import { existsSync } from "node:fs";
import { join } from "node:path";
import type { WindowLine } from "@/components/interview-window";
import { planSession, type PastSession, type SessionPlan } from "@/lib/domain/director";
import { amaF1, kofiB1B2 } from "@/lib/domain/fixtures";

/** Marketing demos are generated by the real engine from fictional sample cases. */

export const HERO_LINE_COUNT = 6;

export function heroQuestions(): { officer: string; voice: string; question: string }[] {
  return Array.from({ length: HERO_LINE_COUNT }, (_, i) => {
    const profile = i % 2 === 0 ? amaF1 : kofiB1B2;
    const plan = planSession({ profile, pastSessions: [], readiness: 0.4, mode: "real", seed: `hero-${i}` });
    return { officer: plan.officer.name, voice: plan.officer.voice, question: plan.probes[0].entry };
  });
}

export const heroAudioPath = (i: number) => `/audio/hero-${i}.wav`;

/** Attaches pre-rendered audio when `pnpm audio:hero` has been run. */
export function heroLines(): WindowLine[] {
  return heroQuestions().map((q, i) => {
    const audio = heroAudioPath(i);
    const exists = existsSync(join(process.cwd(), "public", audio));
    return { officer: q.officer, question: q.question, audioSrc: exists ? audio : undefined };
  });
}

/** Three consecutive sessions for the sample applicant; the first funding answer went badly. */
export function demoSessions(): SessionPlan[] {
  const history: PastSession[] = [];
  const out: SessionPlan[] = [];
  for (let i = 0; i < 3; i++) {
    const plan = planSession({
      profile: amaF1,
      pastSessions: history,
      readiness: 0.2 + i * 0.2,
      mode: i === 2 ? "dress_rehearsal" : "real",
      seed: `homepage-demo-${i}`,
    });
    out.push(plan);
    history.unshift({
      officer: plan.officer,
      askedQuestions: plan.probes.map((p) => p.entry),
      probeResults: plan.probes.map((p) => ({
        probeId: p.probeId,
        quality: i === 0 && p.probeId.includes("funding") ? "weak" : "strong",
        officerName: plan.officer.name,
      })),
    });
  }
  return out;
}
