import type { SessionPlan } from "@/lib/domain/director";

const reasonLabel: Record<SessionPlan["probes"][number]["reason"], string> = {
  untested: "New",
  weak_retest: "Retest, new wording",
  improving: "Confirm",
  case_flag: "From your Case Scan",
  expert_flag: "Coach flagged",
  coverage: "Coverage",
  wildcard: "Curveball",
};

function Trait({ label, value }: { label: string; value: number }) {
  return (
    <div className="flex items-center gap-3 text-xs">
      <span className="w-20 text-white/55">{label}</span>
      <span className="h-1 flex-1 overflow-hidden rounded-full bg-white/10">
        <span className="block h-full rounded-full bg-gold" style={{ width: `${Math.round(value * 100)}%` }} />
      </span>
    </div>
  );
}

export function NeverTheSame({ sessions }: { sessions: SessionPlan[] }) {
  return (
    <section id="never-the-same" aria-labelledby="nts-title" className="grain relative scroll-mt-8 border-y border-line bg-ink text-white">
      <div className="mx-auto max-w-7xl px-4 py-20 sm:px-8 lg:py-28">
        <p className="text-sm uppercase tracking-[0.2em] text-gold">The engine</p>
        <h2 id="nts-title" className="font-display mt-3 max-w-4xl text-[clamp(2.2rem,4.6vw,3.8rem)]">
          No two interviews alike. <em className="text-white/55">Just like the real thing.</em>
        </h2>
        <p className="mt-6 max-w-2xl text-lg leading-relaxed text-white/65">
          A Director plans every session around your case and your weak spots. Then a brand-new officer, who knows
          only what a real officer would see, runs it. Below are three consecutive sessions for one sample applicant,
          generated by the engine this page was built with.
        </p>
        <ol className="mt-14 grid gap-5 lg:grid-cols-3">
          {sessions.map((s, i) => (
            <li key={s.seed} className="reveal flex flex-col rounded-3xl border border-white/10 bg-white/[0.03] p-6">
              <div className="flex items-baseline justify-between">
                <p className="font-mono text-xs uppercase tracking-[0.2em] text-white/45">Session {i + 1}</p>
                <p className="font-mono text-xs text-white/45 tabular">
                  ~{Math.floor(s.targetDurationSec / 60)}:{String(s.targetDurationSec % 60).padStart(2, "0")}
                </p>
              </div>
              <p className="font-display mt-4 text-3xl">{s.officer.name}</p>
              <div className="mt-4 space-y-2">
                <Trait label="Pace" value={s.officer.traits.pace} />
                <Trait label="Warmth" value={s.officer.traits.warmth} />
                <Trait label="Scepticism" value={s.officer.traits.scepticism} />
              </div>
              <ul className="mt-6 space-y-4 border-t border-white/10 pt-5">
                {s.probes.map((p) => (
                  <li key={p.probeId}>
                    <span className="text-[11px] uppercase tracking-[0.16em] text-gold/90">{reasonLabel[p.reason]}</span>
                    <p className="mt-1 leading-snug text-white/85">&ldquo;{p.entry}&rdquo;</p>
                  </li>
                ))}
              </ul>
              {s.events.length > 0 && (
                <p className="mt-auto pt-6 text-xs text-white/45">
                  Also: {s.events.map((e) => e.replaceAll("_", " ")).join(", ")}
                </p>
              )}
            </li>
          ))}
        </ol>
      </div>
    </section>
  );
}
