"use client";

import { useEffect, useRef, useState } from "react";
import { Guilloche } from "./guilloche";

export interface WindowLine {
  officer: string;
  question: string;
  /** Optional pre-rendered officer audio (Gemini 3.8 Flash TTS, see scripts/). */
  audioSrc?: string;
}

function prefersReducedMotion() {
  return typeof window !== "undefined" && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
}

const fmt = (s: number) => `${String(Math.floor(s / 60)).padStart(2, "0")}:${String(s % 60).padStart(2, "0")}`;

/**
 * The hero's interview document. Each tap is a different officer asking a
 * question generated by the real Director. The clock counts up: real
 * interviews have no fixed length.
 */
export function InterviewWindow({ lines }: { lines: WindowLine[] }) {
  const [index, setIndex] = useState(-1);
  const [chars, setChars] = useState(0);
  const [startedAt, setStartedAt] = useState<number | null>(null);
  const [elapsed, setElapsed] = useState(0);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  const line = index >= 0 ? lines[index % lines.length] : null;
  const shown = line ? line.question.slice(0, chars) : "";
  const speaking = line !== null && chars < line.question.length;

  useEffect(() => {
    if (!line || chars >= line.question.length) return;
    const timer = window.setTimeout(() => setChars((c) => c + 1), 32);
    return () => window.clearTimeout(timer);
  }, [line, chars]);

  useEffect(() => {
    if (startedAt === null) return;
    const t = window.setInterval(() => setElapsed(Math.floor((Date.now() - startedAt) / 1000)), 250);
    return () => window.clearInterval(t);
  }, [startedAt]);

  function ask() {
    const next = lines[(index + 1) % lines.length];
    setIndex((i) => i + 1);
    setChars(prefersReducedMotion() ? next.question.length : 0);
    if (startedAt === null) setStartedAt(Date.now());
    if (next.audioSrc) {
      audioRef.current?.pause();
      audioRef.current = new Audio(next.audioSrc);
      audioRef.current.play().catch(() => {});
    }
  }

  return (
    <div className="doc relative overflow-hidden">
      <Guilloche className="guilloche pointer-events-none absolute -right-40 -top-40 w-[520px]" />
      <div className="relative flex items-center justify-between border-b border-ink px-5 py-3">
        <span className="label">Window 07 · Nonimmigrant visas</span>
        <span className="label tabular" aria-label="Time at the window">
          {fmt(elapsed)}
        </span>
      </div>

      <div className="relative min-h-[300px] px-5 pb-6 pt-8 sm:min-h-[340px] sm:px-8">
        <div className="flex min-h-10 items-start justify-between gap-4">
          <p className="label text-muted">{line ? "The officer asks" : "Queue no. A-114"}</p>
          {line && (
            <span key={index} className="stamp stamp-press text-stamp">
              {line.officer}
            </span>
          )}
        </div>
        <p aria-live="polite" className="font-voice mt-4 text-[clamp(1.9rem,3.6vw,2.9rem)] leading-[1.08]">
          {line ? (
            <>
              &ldquo;{shown}
              {speaking ? <span className="caret" /> : "”"}
            </>
          ) : (
            <span className="text-muted">Your number is called. Step up to the window.</span>
          )}
        </p>
      </div>

      <div className="perforated" />
      <div className="relative flex flex-wrap items-center justify-between gap-3 px-5 py-4 sm:px-8">
        <p className="max-w-xs text-sm text-muted">
          {index < 0
            ? "Every tap is a different officer, with a question about a sample applicant's real case."
            : speaking
              ? "Listen…"
              : "Answer out loud. Short and true beats long and rehearsed."}
        </p>
        <button
          type="button"
          onClick={ask}
          className="rounded-[3px] bg-ink px-5 py-3 text-sm font-semibold text-on-ink transition hover:bg-stamp"
        >
          {index < 0 ? "Call the next applicant" : "Next officer →"}
        </button>
      </div>
    </div>
  );
}
